// <auto-generated />
using System;
using Maxtrain.MaxCoin.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Maxtrain.MaxCoin.Migrations
{
    [DbContext(typeof(MaxCoinDbContext))]
    partial class MaxCoinDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Maxtrain.MaxCoin.Models.Block", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Data");

                    b.Property<string>("Hash");

                    b.Property<int>("Nonce");

                    b.Property<string>("PrevHash");

                    b.Property<DateTime>("Timestamp");

                    b.HasKey("Index");

                    b.ToTable("Blocks");
                });

            modelBuilder.Entity("Maxtrain.MaxCoin.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Flag");

                    b.Property<int>("InCounter");

                    b.Property<string>("Inputs");

                    b.Property<DateTime?>("LockTime");

                    b.Property<int>("OutCounter");

                    b.Property<string>("Outputs");

                    b.Property<int>("Version");

                    b.Property<string>("Witnesses");

                    b.HasKey("Id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
